WhiteHotel/Controllers/VillaController.cs
using Microsoft.AspNetCore.Mvc;
using WhiteHotel.Application.Common.Interfaces;
using WhiteHotel.Domain.Entities;
using WhiteHotel.Infrastructure.Data;

namespace WhiteHotel.Web.Controllers
{
    public class VillaController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public VillaController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment; 
        }
        public IActionResult Index()
        {
            var villas = _unitOfWork.Villa.GetAll();
            return View(villas);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Villa villa)
        {
            if (villa.Name==villa.Description)
            {
                ModelState.AddModelError("Description", "the description cannot br exactly match the Name.");
            }
            if (ModelState.IsValid) 
            {
                if (villa.Image!=null)
                {
                    string fileName = Guid.NewGuid().ToString()+ Path.GetExtension(villa.Image.FileName);
                    string ImagePath = Path.Combine(_webHostEnvironment.WebRootPath, @"images\VillaImage");
                    using var fileStream = new FileStream(Path.Combine(ImagePath,fileName), FileMode.Create);
                    villa.Image.CopyTo(fileStream);
                    villa.ImageUrl = @"\images\VillaImage\" + fileName;
                }
                else
                {
                    villa.ImageUrl = "https://th.bing.com/th/id/OIP.LHY-huRGQF7Xcn4GvYjz9AAAAA?rs=1&pid=ImgDetMain";
                }
                _unitOfWork.Villa.Add(villa);
                _unitOfWork.Save();
                TempData["success"] = "the villa has been created successfully.";
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Update(int validId)
        {
            var villa = _unitOfWork.Villa.Get(x => x.Id == validId);
            if(villa == null)
            {
                return RedirectToAction("Error","Home");
            }
            return View(villa);
        }
        [HttpPost]
        public IActionResult Update(Villa villa)
        {

          
            if (ModelState.IsValid && villa.Id>0)
            {
                if (villa.Image != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(villa.Image.FileName);
                    string ImagePath = Path.Combine(_webHostEnvironment.WebRootPath, @"images\VillaImage");
                    if (!string.IsNullOrEmpty(villa.ImageUrl))
                    {
                        var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, villa.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }
                    using var fileStream = new FileStream(Path.Combine(ImagePath, fileName), FileMode.Create);
                    villa.Image.CopyTo(fileStream);
                    villa.ImageUrl = @"\images\VillaImage\" + fileName;
                }

                _unitOfWork.Villa.Update(villa);
                _unitOfWork.Save();
                TempData["success"] = "the villa has been updated successfully.";
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Delete(int validId)
        {
            var villa = _unitOfWork.Villa.Get(x => x.Id == validId);
            if (villa is null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(villa);
        }
        [HttpPost]
        public IActionResult Delete(Villa villa)
        {
            var villaFromDb = _unitOfWork.Villa.Get(x=>x.Id == villa.Id);
            if (villaFromDb is not null)
            {
                if (!string.IsNullOrEmpty(villaFromDb.ImageUrl))
                {
                    var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, villaFromDb.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }
                _unitOfWork.Villa.Remove(villaFromDb);
                _unitOfWork.Save();
                TempData["success"] = "the villa has been deleted successfully.";
                return RedirectToAction("Index");
            }
            TempData["erorr"] = "the villa could not be deleted.";

            return View();
        }

    }
}

WhiteHotel/Views/Villa/Create.cshtml
@model Villa


<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create Villa</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
            <form method="post" class="row" enctype="multipart/form-data">
                <div class="p-3">
                    @* <div asp-validation-summary="ModelOnly"></div> *@
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Name" class="form-control border shadow" />
                        <label asp-for="Name" class="control-label"></label>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Description" class="form-control border shadow" />
                        <label asp-for="Description" class="control-label"></label>
                        <span asp-validation-for="Description" class="text-danger"></span>

                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Price" class="form-control border shadow" />
                        <label asp-for="Price" class="control-label"></label>
                        <span asp-validation-for="Price" class="text-danger"></span>

                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Sqft" class="form-control border shadow" />
                        <label asp-for="Sqft" class="control-label"></label>
                    <span asp-validation-for="Sqft" class="text-danger"></span>

                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Occupancy" class="form-control border shadow" />
                        <label asp-for="Occupancy" class="control-label"></label>
                    <span asp-validation-for="Occupancy" class="text-danger"></span>

                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Image" class="form-control border shadow" />
                        <label asp-for="ImageUrl" class="control-label"></label>
                    <span asp-validation-for="ImageUrl" class="text-danger"></span>

                    </div>
                    <div class="row pt-2">
                        <div class="col-6 col-md-3">
                            <button type="submit" class="btn btn-success w-100">
                                <i class=" bi bi-check-circle"></i>Create
                            </button>
                        </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i>Cancel
                        </a>
                    </div>
                    </div>
                </div>
            </form>
        </div>
</div>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

WhiteHotel/Views/Villa/Delete.cshtml
@model Villa

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Delete Villa</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row">
            <input asp-for="Id" hidden />
            <div class="col-10">
            <div class="p-3">
                @* <div asp-validation-summary="ModelOnly"></div> *@
                <div class="form-floating py-1 col-12">
                    <input asp-for="Name" disabled class="form-control border shadow" />
                    <label asp-for="Name" class="control-label"></label>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Description" disabled class="form-control border shadow" />
                    <label asp-for="Description" class="control-label"></label>

                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Price" disabled class="form-control border shadow" />
                    <label asp-for="Price" class="control-label"></label>

                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Sqft" disabled class="form-control border shadow" />
                    <label asp-for="Sqft" class="control-label"></label>

                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Occupancy" disabled class="form-control border shadow" />
                    <label asp-for="Occupancy" class="control-label"></label>

                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="ImageUrl" disabled class="form-control border shadow" />
                    <label asp-for="ImageUrl" class="control-label"></label>

                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-danger w-100">
                            <i class=" bi bi-trash-fill"></i>Delete
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i>Cancel
                        </a>
                    </div>
                </div>
            </div>
                </div>
            <div class="col-2">
                <img src="@Model.ImageUrl" width="100%"
                     style="border-radius:5px; border:1px solid #bbb9b9" />
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

WhiteHotel/Views/Villa/Edit.cshtml
@model Villa

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Update Villa</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row">
            <input asp-for="Id" hidden/>
            <div class="p-3">
                @* <div asp-validation-summary="ModelOnly"></div> *@
                <div class="form-floating py-1 col-12">
                    <input asp-for="Name" class="form-control border shadow" />
                    <label asp-for="Name" class="control-label"></label>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Description" class="form-control border shadow" />
                    <label asp-for="Description" class="control-label"></label>
                    <span asp-validation-for="Description" class="text-danger"></span>

                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Price" class="form-control border shadow" />
                    <label asp-for="Price" class="control-label"></label>
                    <span asp-validation-for="Price" class="text-danger"></span>

                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Sqft" class="form-control border shadow" />
                    <label asp-for="Sqft" class="control-label"></label>
                    <span asp-validation-for="Sqft" class="text-danger"></span>

                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Occupancy" class="form-control border shadow" />
                    <label asp-for="Occupancy" class="control-label"></label>
                    <span asp-validation-for="Occupancy" class="text-danger"></span>

                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="ImageUrl" class="form-control border shadow" />
                    <label asp-for="ImageUrl" class="control-label"></label>
                    <span asp-validation-for="ImageUrl" class="text-danger"></span>

                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class=" bi bi-check-circle"></i>Update
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i>Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

WhiteHotel/Views/Villa/Index.cshtml
@model IEnumerable<Villa>

   <div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Villa List</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <div class="row pb-3">
                <div class="col-6 offset-6 text-end">
                <a asp-controller="Villa" asp-action="Create" class="btn btn-secondary"><i class="bi bi-plus-circle"></i>  Add New Villa</a>
                </div>
        </div>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Price</th>
                    <th scope="col">Sqft</th>
                    <th scope="col">Occupany</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td>@item.Price</td>
                        <td>@item.Sqft</td>
                        <td>@item.Occupancy</td>
                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Villa" asp-action="Update" asp-route-validId="@item.Id" 
                                    class="btn btn-success mx-2">
                                    <i class="bi bi-pencil-square"></i> Edit
                                </a>
                                <a asp-controller="Villa" asp-action="Delete" asp-route-validId="@item.Id"
                                   class="btn btn-danger mx-2">
                                    <i class="bi bi-trash-fill"></i> Delete
                                </a>
                            </div>
                        </td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
   </div>

WhiteHotel/Views/Villa/Update.cshtml
@model Villa


<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Update Villa</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Id" hidden />
            <div class="col-10">
                <div class="p-3">
                    @* <div asp-validation-summary="ModelOnly"></div> *@
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Name" class="form-control border shadow" />
                        <label asp-for="Name" class="control-label"></label>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Description" class="form-control border shadow" />
                        <label asp-for="Description" class="control-label"></label>
                        <span asp-validation-for="Description" class="text-danger"></span>

                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Price" class="form-control border shadow" />
                        <label asp-for="Price" class="control-label"></label>
                        <span asp-validation-for="Price" class="text-danger"></span>

                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Sqft" class="form-control border shadow" />
                        <label asp-for="Sqft" class="control-label"></label>
                        <span asp-validation-for="Sqft" class="text-danger"></span>

                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Occupancy" class="form-control border shadow" />
                        <label asp-for="Occupancy" class="control-label"></label>
                        <span asp-validation-for="Occupancy" class="text-danger"></span>

                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Image" class="form-control border shadow" />
                        <input asp-for="ImageUrl" hidden class="form-control border shadow" />
                        <label asp-for="ImageUrl" class="control-label"></label>
                        <span asp-validation-for="ImageUrl" class="text-danger"></span>

                    </div>
                    <div class="row pt-2">
                        <div class="col-6 col-md-3">
                            <button type="submit" class="btn btn-success w-100">
                                <i class=" bi bi-check-circle"></i>Update
                            </button>
                        </div>
                        <div class="col-6 col-md-3">
                            <a asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100">
                                <i class="bi bi-x-circle"></i>Cancel
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-2">
                <img src="@Model.ImageUrl" width="100%"
                style="border-radius:5px; border:1px solid #bbb9b9"/>
            </div>
           
        </form>
    </div>
</div>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}