WhiteHotel/ViewModels/VillaNumberViewModel.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.Rendering;
using WhiteHotel.Domain.Entities;

namespace WhiteHotel.Web.ViewModels
{
    public class VillaNumberViewModel
    {
        public VillaNumber? VillaNumber { get; set; }
        [ValidateNever]
        public IEnumerable<SelectListItem>? VillaList { get; set; }
    }
}

WhiteHotel/Controllers/VillaNumberController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WhiteHotel.Application.Common.Interfaces;
using WhiteHotel.Domain.Entities;
using WhiteHotel.Infrastructure.Data;
using WhiteHotel.Web.ViewModels;

namespace WhiteHotel.Web.Controllers
{
    public class VillaNumberController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;
        public VillaNumberController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            var villaNumbers = _unitOfWork.VillaNumber.GetAll(includeProperites: "Villa");
            return View(villaNumbers);
        }

        public IActionResult Create()
        {
            VillaNumberViewModel villaNumber = new()
            {
                VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                })
            };
            
            return View(villaNumber);
        }
        [HttpPost]
        public IActionResult Create(VillaNumberViewModel obj)
        {

           bool roomNumberExist = _unitOfWork.VillaNumber.Any(u=>u.Villa_Number==obj.VillaNumber.Villa_Number);
            if (ModelState.IsValid && !roomNumberExist ) 
            {
                _unitOfWork.VillaNumber.Add(obj.VillaNumber);
                _unitOfWork.Save();
                TempData["success"] = "the villa has been created successfully.";
                return RedirectToAction("Index");
            }
            if (roomNumberExist)
            {
                TempData["error"] = "this villa number already exists";
            }
            obj.VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString(),
            });
            return View(obj);
        }
        public IActionResult Update(int villaNumberId)
        {
            VillaNumberViewModel villaNumbermv = new()
            {
                VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                }),
                VillaNumber = _unitOfWork.VillaNumber.Get(d => d.Villa_Number == villaNumberId)
            };

            if(villaNumbermv.VillaNumber == null)
            {
                return RedirectToAction("Error","Home");
            }
            return View(villaNumbermv);
        }
        [HttpPost]
        public IActionResult Update(VillaNumberViewModel villaNumberViewModel)
        {

            if (ModelState.IsValid)
            {
                _unitOfWork.VillaNumber.Update(villaNumberViewModel.VillaNumber);
                _unitOfWork.Save();
                TempData["success"] = "the villa has been updated successfully.";
                return RedirectToAction("Index");
            }
           
            villaNumberViewModel.VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString(),
            });
            return View(villaNumberViewModel);
        }
        public IActionResult Delete(int villaNumberId)
        {
            VillaNumberViewModel villaNumbermv = new()
            {
                VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                }),
                VillaNumber = _unitOfWork.VillaNumber.Get(d => d.Villa_Number == villaNumberId)
            };

            if (villaNumbermv.VillaNumber == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(villaNumbermv);
        }
        [HttpPost]
        public IActionResult Delete(VillaNumberViewModel villaNumberViewModel)
        {
            VillaNumber? villaNumber = _unitOfWork.VillaNumber.Get(d => d.Villa_Number == villaNumberViewModel.VillaNumber.Villa_Number); 
            if (villaNumber is not null)
            {
                _unitOfWork.VillaNumber.Remove(villaNumber);
                _unitOfWork.Save();
                TempData["success"] = "the villa number has been deleted successfully.";
                return RedirectToAction("Index");
            }
            TempData["error"] = "the villa number could not be deleted.";

            
            return View();
        }

    }
}

WhiteHotel/Views/VillaNumber/Create.cshtml
@model VillaNumberViewModel



<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create Villa</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row">
            <div class="p-3">
                @* <div asp-validation-summary="ModelOnly"></div> *@

                <div class="form-floating py-1 col-12">
                    <select asp-for="@Model.VillaNumber.VillaId" asp-items="@Model.VillaList"
                        class="form-control border shadow">
                        <option disabled selected>--Select Villa--</option>
                        </select>
                    <label asp-for="VillaNumber.VillaId" class="control-label"></label>
                    <span asp-validation-for="VillaNumber.VillaId" class="text-danger"></span>

                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="VillaNumber.Villa_Number" class="form-control border shadow" />
                    <label asp-for="VillaNumber.Villa_Number" class="control-label"></label>
                    <span asp-validation-for="VillaNumber.Villa_Number" class="text-danger"></span>

                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="VillaNumber.SpecialDetails" class="form-control border shadow" />
                    <label asp-for="VillaNumber.SpecialDetails" class="control-label"></label>
                    <span asp-validation-for="VillaNumber.SpecialDetails" class="text-danger"></span>

                </div>
          
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class=" bi bi-check-circle"></i>Create
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="VillaNumber" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i>Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

WhiteHotel/Views/VillaNumber/Delete.cshtml
@model VillaNumberViewModel



<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Update Villa Number</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row">
            <input asp-for="VillaNumber.Villa_Number" hidden />
            <div class="p-3">
                @* <div asp-validation-summary="ModelOnly"></div> *@

                <div class="form-floating py-1 col-12">
                    <select disabled asp-for="@Model.VillaNumber.VillaId" asp-items="@Model.VillaList"
                            class="form-control border shadow">
                        <option disabled selected>--Select Villa--</option>
                    </select>
                    <label asp-for="VillaNumber.VillaId" class="control-label"></label>
                    <span asp-validation-for="VillaNumber.VillaId" class="text-danger"></span>

                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="VillaNumber.Villa_Number" disabled class="form-control border shadow" />
                    <label asp-for="VillaNumber.Villa_Number" class="control-label"></label>
                    <span asp-validation-for="VillaNumber.Villa_Number" class="text-danger"></span>

                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="VillaNumber.SpecialDetails" disabled class="form-control border shadow" />
                    <label asp-for="VillaNumber.SpecialDetails" class="control-label"></label>
                    <span asp-validation-for="VillaNumber.SpecialDetails" class="text-danger"></span>

                </div>

                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-danger w-100">
                            <i class=" bi bi-check-circle"></i>Delete
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="VillaNumber" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i>Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

WhiteHotel/Views/VillaNumber/Index.cshtml
@model IEnumerable<VillaNumber>

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">VillaNumber List</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <div class="row pb-3">
            <div class="col-6 offset-6 text-end">
                <a asp-controller="VillaNumber" asp-action="Create" class="btn btn-secondary"><i class="bi bi-plus-circle"></i>  Add New VillaNumber</a>
            </div>
        </div>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th scope="col">Nilla Name</th>
                    <th scope="col">Villa Number</th>
                    <th scope="col">Speical Details</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Villa.Name</td>
                        <td>@item.Villa_Number</td>
                        <td>@item.SpecialDetails</td>
                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="VillaNumber" asp-action="Update" asp-route-villaNumberId="@item.Villa_Number"
                                   class="btn btn-success mx-2">
                                    <i class="bi bi-pencil-square"></i> Edit
                                </a>
                                <a asp-controller="VillaNumber" asp-action="Delete" asp-route-villaNumberId="@item.Villa_Number"
                                   class="btn btn-danger mx-2">
                                    <i class="bi bi-trash-fill"></i> Delete
                                </a>
                            </div>
                        </td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
</div>

WhiteHotel/Views/VillaNumber/Update.cshtml
@model VillaNumberViewModel



<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Update Villa Number</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row">
            <input asp-for="VillaNumber.Villa_Number" hidden/>
            <div class="p-3">
                @* <div asp-validation-summary="ModelOnly"></div> *@

                <div class="form-floating py-1 col-12">
                    <select asp-for="@Model.VillaNumber.VillaId" asp-items="@Model.VillaList"
                            class="form-control border shadow">
                        <option disabled selected>--Select Villa--</option>
                    </select>
                    <label asp-for="VillaNumber.VillaId" class="control-label"></label>
                    <span asp-validation-for="VillaNumber.VillaId" class="text-danger"></span>

                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="VillaNumber.Villa_Number" disabled class="form-control border shadow" />
                    <label asp-for="VillaNumber.Villa_Number" class="control-label"></label>
                    <span asp-validation-for="VillaNumber.Villa_Number" class="text-danger"></span>

                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="VillaNumber.SpecialDetails" class="form-control border shadow" />
                    <label asp-for="VillaNumber.SpecialDetails" class="control-label"></label>
                    <span asp-validation-for="VillaNumber.SpecialDetails" class="text-danger"></span>

                </div>

                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class=" bi bi-check-circle"></i>Update
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="VillaNumber" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i>Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}